# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo:7.0.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: develop
    ports:
      - "27017:27017"
    volumes:
      - mongo1-data:/data/db

volumes:
  mongo1-data: